### ISSUE TITLE
Fix/rework buttons in menu at gh-pages

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea#2]
On a mobile device (small screen), the buttons in the menu (HOME, OpenWRT Probe, TRAP Interface Specifier) are not visible.

The task is to display some "menu" button on small screens that would allow users to switch pages.

In addition, active (currently opened) page should be shown in a different color of the button.

**Comment by ladislavmacoun** [comment]
Fixed by commit: 591a21e
